[tool.poetry]
name = "readme-ai-ui"
version = "0.1.0"
description = "🪄 Streamlit app for generating README.md files, powered by OpenAI's GPT LLMs ✨"
authors = ["Eli <43382407+eli64s@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "readme_ai_ui"}]

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.25.0"
readmeai = "^0.1.6"

[tool.poetry.group.dev.dependencies]
black = "*"
flake8 = "*"
isort = "*"
ruff = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
