[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "readmeai-ui"
version = "0.1.0"
description = "Streamlit app serving the readmeai cli tool."
authors = ["Eli <43382407+eli64s@users.noreply.github.com>"]
license = "Apache-2.0"
readme = "README.md"
keywords = [
    "readme",
    "streamlit",
    "streamlit-llm", 
    "streamlit-gpt",
    "openai-api",
]

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<4.0"
streamlit = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-randomly = "*"
pytest-sugar = "*"
