[tool.poetry]
name = "src"
version = "0.1.0"
description = "Automated README file generator 🧚‍♀️"
authors = ["Eli <egsalamie@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
keywords = [
    "python",
    "readme",
    "documentation",
    "readme-generator",
    "streamlit",
    "streamlit-ai",
    "streamlit-cloud",
    "streamlit-gpt",
    "streamlit-llm",
    "llm",
]

[tool.poetry.dependencies]
python = "^3.9,<4.0.0"
readmeai = "0.5.86"
streamlit = "*"

[tool.poetry.group.dev.dependencies]
mypy = "*"
pre-commit = "*"
ruff = "*"

[tool.poetry.group.test.dependencies]
pytest = "=7.4.4"
pytest-cov = "*"
pytest-randomly = "*"
pytest-sugar = "*"
pytest-xdist = "*"

[tool.pytest.ini_options]
addopts = [
    "-vvv",
    "-rfEsxX",
    "--durations=10",
    "--asyncio-mode=auto",
    "--numprocesses=auto",
    "--cov=readmeai",
    "--cov-branch",
    "--cov-report=xml",
    "--cov-report=term-missing",
]
env = [
    "OLLAMA_HOST=127.0.0.1",
]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.coverage.report]
exclude_also = [
    "if __name__ == '__main__':",
    "pragma: no cover",
    "raise NotImplementedError",
]
fail_under = 80
precision = 2
show_missing = true
skip_covered = true
skip_empty = true
sort = "cover"
omit = [
    "tests/*",
    "*__init__.py",
    "*/__init__.py",
]

[build-system]
requires = ["poetry-core", "setuptools"]
build-backend = "poetry.core.masonry.api"