[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "src"
version = "0.1.0"
description = "🧚‍♀️ Generate beautiful README automatically on Streamlit"
authors = ["Eli <0x.eli.64s@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
keywords = [
    "streamlit",
    "streamlit-cloud",
    "streamlit-llm",
    "streamlit-gpt",
    "streamlit-ai",
    "readme-generator",
    "openai-api",
    "llms",
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
streamlit = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-randomly = "*"
pytest-sugar = "*"
pytest-xdist = "*"